### ISSUE TITLE
Multishipping in Magento 2

### ISSUE THREAD

**Issue by davidzach** [wirecard/magento2-ee#130]
When multishipping checkout with Magento 2 is used, no payment options from wirecard are displayed.

Steps to Reproduce:
1)	install Magento: 2.2.x,
2)	install "wirecard/magento2-ee": "^1.3.5",
3)	enable mutishipping: https://www.humcommerce.com/tutorial/setup-multishipping-magento-2/
4)	Add multiple products to the cart
5)	Start the checkout via URL: https://{domain}/multishipping/checkout/addresses/

**Comment by rinnhofer** [comment]
Hello,
thank your for your contribution we will look into it as soon as possible.

Kind regards

**Comment by serucee** [comment]
Hello,

currently our extension does not support multishipping. This information will be added to our WIKI.
In the future we might add support for multishipping depending on the usage of this feature.

Kind regards,
Wirecard Shop Systems Team
