### ISSUE TITLE
Logging in default files

### ISSUE THREAD

**Issue by FerihumF** [wirecard/magento2-ee#133]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.1.11
**PHP version:** 7.0.11

### Issue

**Problem description:**

Logging of payment request information etc. spams default log files. On a production server this can get frustrating. I suggest creating a custom folder in var/log/ for wirecard specific logs. Also the debugging part should be a configuration (yes/no) in the backend since it there is gathering quite some information.

**Comment by jakubpolomsky** [comment]
Hello Fabian,

thank you for your feedback! I would like to show you one site which might help you https://magento.stackexchange.com/questions/133156/magento-2-turn-on-off-debug-log.

Our Magento 2 plugin implements the standard Logger-Interface built into the Shop. Therefore if you wish to limit the logs just to some level change the logging settings please.

Thanks once again!

Kind regards
