### ISSUE TITLE
Incorrect First & Last name with Credit Card Payment

### ISSUE THREAD

**Issue by thomas-WD** [wirecard/magento2-ee#164]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.2.6
**PHP version:** 7.1.23

### Issue

**Problem description:**
Wirecard credit card uses the Mangento shipper's first & last name, but not the credit card first and last name entered during credit card detail entry. 
...

**Steps to reproduce:**
Use the credit payment, enter "firstname" in the First name and "lastname" in the Last name field. Complete the order.
Check the transaction detail in EE or WEP. The First name and Last name are not  "firstname" & "lastname" respectively.

...

**Comment by jakubpolomsky** [comment]
Hello,

this is not an error in the plugin but a configuration option in the gateway. I would recommend you to contact our support as there are personal informations included in your configuration which we don't want to show publicly. Therefore contact us from within our extension (the fastest option) or write us an email to shop-systems-support@wirecard.com as stated here https://github.com/wirecard/magento2-ee/wiki/Contact-Information

Kind regards,
Wirecard Team
