### ISSUE TITLE
Occasionally orders placed with no Transaction record. M2 2.2.6 Module 1.3.11

### ISSUE THREAD

**Issue by tim-reynolds-visionet** [wirecard/magento2-ee#190]
### Prerequisites

- [X] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [X] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** ... 2.2.6 
**PHP version:** ... 7.1  

### Issue

We have had 4 orders placed since January 1st where the order successfully places, the authorization correctly appears in Wirecard, but no record is created in the sales_order_payment table. We cannot find any logs around this, and we can't find any pattern to this other than the first two times this happened it was in quick succession by the same user. 

Our assumption is something is failing when writing the transaction record so that is failing but then at that point the sales_order record is already written and the authorization already made. I have not been able to test this yet as I don't know how to recreate it. 

I am mostly posting this to see if you have heard of this happening or have any insight. I don't believe we have any plugins to your module or to the sales order pipeline that could be causing this, and we have thousands and thousands of orders that go through without issue. 

Other Details:
The first two orders were in Euros, the second two in Yen.

...

**Steps to reproduce:**
We can't yet reproduce this. 
...
Thank you for any time you can give to looking into this. We really appreciate it.

**Comment by jakubpolomsky** [comment]
Hello Mr. Reynolds,

we haven't noticed this behavior before. The entries in the table aren't actually controlled by the plugin. The order model is taking care of this and we can just order the model to create a transaction and see whether it was successful or not. The only thing that is known is that the columns base_shipping_captured, shipping_captured and base_amount_paid can stay empty even if the payment action was set to purchase (for e.g. Credit Card). When this happens, the usual suspect is the firewall blocking our asynchronous notifications which are sent independently of the front-end redirects and requests. The firewall rules then have to be opened for the inbound communication from our gateways.

I will close this request, but when this occurs again, could you please reopen it?

Kind regards
