### ISSUE TITLE
Checkout Agreements

### ISSUE THREAD

**Issue by flamboy85** [wirecard/magento2-ee#207]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.0 
**PHP version:** 7.2
**Wirecard ElasticEngine version:**1.4.1

### Issue

**Problem description:**
Installed latest module version 
Module throw error on frontend with enabled option 'Term & conditions'

**Steps to reproduce:**

Enable admin option 'checkout/options/enable_agreements'
Enable 'payment/wirecard_elasticengine_creditcard/active'
Try to process checkout page

**Comment by rinnhofer** [comment]
Hello @flamboy85,

thank you for your contribution. We are currently working on a solution for this issue and will inform you as soon as it is finished.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @flamboy85 ,

today we released a new version of our module, which should resolve this issue:
https://github.com/wirecard/magento2-ee/tree/1.4.3

Kind regards,
Wirecard Shop Systems Team
