### ISSUE TITLE
Missing Firewall info

### ISSUE THREAD

**Issue by JohnBort** [wirecard/magento2-ee#213]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.2.6
**PHP version:** 7.1 

### Issue

**Problem description:**

The extension seems to receive asynchronous notification from the wirecard gateways. This fact is not stated in the wiki and the information which firewall rules have to be implemented is missing.

**Steps to reproduce:**

1. Install the extension on a system behind a firewall
1. Activate a payment solution with asynchronous notifications (i.e. credit card)
1. Place an order with said solution

The order will receive the status "Pending Payment" and will not be updated.

**Comment by rinnhofer** [comment]
Hello @JohnBort,

thank you for your contribution. We will consider to put this information into our documentation here on GitHub.
I hope you were able to configure your firewall rules accordingly in the mean time. If you need help with the set up please feel free to contact `shop-systems-support@wirecard.com` for more personal support.

Kind regards,
Wirecard Shop Systems Team

**Comment by vitali-graz** [comment]
Hello @JohnBort 

I will close this ticket for now. Communication of firewall settings is handled by our internal documentation team as part of the ongoing effort of improving our wiki.

Best regards,
Wirecard Shop Systems Team
