### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by murilopereirame** [wirecard/magento2-ee#218]
### Prerequisites

- [ CHECK ] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [ CHECK ] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.1
**PHP version:** 7.1  

### Issue

**Problem description:**

I've installed the module in my server and tried to upgrade/compile magento, but I recieve the error 

PHP Fatal error:  Trait 'Wirecard\ElasticEngine\Controller\Frontend\NoCsrfTrait' not found in /var/www/html/app/code/Wirecard/ElasticEngine/Controller/Frontend/Notify.php on line 63

The respective line is use NoCsrfTrait;

**Steps to reproduce:**

1º Install the module
2º Try magento:upgrade

**Comment by rinnhofer** [comment]
Hello @murilopereirame ,

sorry to check again, but it is not clear how you installed the module, can you please verify that you installed our module with the following commands in /var/www/html ?
1. composer require wirecard/magento2-ee
2. bin/magento setup:upgrade
3. bin/magento setup:di:compile

It could be that there is a problem with the required version of our module and that you have the specify the module version.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Since there is no update on this issue I hope it already resolved and close it for now. If there still problems feel free to reopen it or to create a new issue.

Kind regards,
Wirecard Shop Systems Team

**Comment by rishabhbahukhandi03** [comment]
Using version ^3.1 for wirecard/magento2-ee
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed

please help with this error
