### ISSUE TITLE
PHP 7.1, 7.2 and 7.3 support

### ISSUE THREAD

**Issue by MarcusWolschon** [wirecard/magento2-ee#224]
According to
https://github.com/wirecard/magento2-ee/releases
the current release is not compatible with PHP 7.2 .

This should be fixed as the listed Magento 2.3 is requires
PHP 7.1 or 7.2 and does not even support such old PHP versions anymore.
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by rinnhofer** [comment]
Hello @MarcusWolschon ,

thank you for your contribution. Seems that a mistake happened within our release publishing, at least PHP 7.1 is supported for our current release.
Testing our extension with PHP 7.2 compatibility is planned soon and we will give you an update here when it happened.

Kid regards,
Wirecard Shop Systems Team

**Comment by MarcusWolschon** [comment]
The Readme.md still says PHP7.0

https://raw.githubusercontent.com/wirecard/magento2-ee/master/README.md

**Comment by YiffyToys** [comment]
**new release 1.5.2 from 2 days ago** but it says
"Tested version(s): Magento Community Edition 2.3.0 with PHP 7.0 and PHP 7.1
Compatibility: Magento Community Edition 2.1.4 - 2.3.0 with PHP 7.0 and PHP 7.1 "
Not compatible or tested with 2.3.2 from **last month** that is "certified and tested on PHP 7.2.11"?
Or even 2.3.1 from **4 month ago**.

**Comment by serucee** [comment]
Hi,

@MarcusWolschon The Readme was updated to include PHP 7.1
@YiffyToys The extension is currently tested with the magento community edition 2.3.1 - I updated the readme and release notes accordingly. We will test our extension with the 2.3.2 version as soon as possible and inform you once done.

**Comment by serucee** [comment]
Hi @MarcusWolschon 
@YiffyToys 
The extension is now compatible and tested with PHP 7.2 and magento 2.3.2.
PHP 7.3 will be tested at a later point.
When updating please follow the steps listed in the release notes https://github.com/wirecard/magento2-ee/releases/tag/2.2.0

Best regards,
Wirecard Shop Systems Team

**Comment by YiffyToys** [comment]
Thanks for the info
We have already cancelled our contract with Wirecard quite a while ago
as we could not affort to not accept credit cards for serveral month
and did not want to pay the monthly fees without getting the service.
