### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by regandor** [wirecard/magento2-ee#229]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.1.11
**PHP version:** 7.0.33

### Issue

**Problem description:**

`Errors during compilation:
	Wirecard\ElasticEngine\Controller\Frontend\Creditcard
		Incorrect dependency in class Wirecard\ElasticEngine\Controller\Frontend\Creditcard in /var/www/my-project/vendor/wirecard/magento2-ee/Controller/Frontend/Creditcard.php
\Magento\Framework\UrlInterface already exists in context object
	Wirecard\ElasticEngine\Controller\Frontend\Callback
		Incorrect dependency in class Wirecard\ElasticEngine\Controller\Frontend\Callback in /var/www/my-project/vendor/wirecard/magento2-ee/Controller/Frontend/Callback.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 2
`

**Steps to reproduce:**

1 . composer require wirecard/magento2-ee
2 . php bin/magento setup:upgrade
3 . php bin/magento setup:di:compile

**Comment by rinnhofer** [comment]
Hello @regandor ,

thank you for you contribution. We will check if we can reproduce this behaviour for now we did not discover an error during installation and update process.

Kind regards,
Wirecard Shop Systems Team

**Comment by budaoander** [comment]
Dear @rinnhofer ,

Thank you for your answer. Fo you have update on this issue?

Kind Regards,
Gabor

**Comment by rinnhofer** [comment]
Hello @regandor and @budaoander ,

we could reproduce the compile error with this specific magento2 version. Seems like we missed this within our automatic tests. To resolve this issue we will need additional time, so please use a previous version of our extension 1.4.3 for example, to resolve the issue for now.
We will notice you as soon as we have a solution within our newest release.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @regandor  and @budaoander ,

today we released a new version of our magento2 extension which should resolve the issue with UrlInterface during compilation
https://github.com/wirecard/magento2-ee/releases/tag/1.5.2

Kind regards,
Wirecard Shop Systems Team
