### ISSUE TITLE
redirected to checkout/undefined

### ISSUE THREAD

**Issue by roman204** [wirecard/magento2-ee#230]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.1  
**PHP version:** 7.0

### Issue

**Problem description:**
After clicking the "order now" button the user gets redireced to the url checkout/undefined
...

**Steps to reproduce:**

...
the reason is a wrong response from the controller, see the following screenshots

![Auswahl_351](https://user-images.githubusercontent.com/584168/58243143-695bf280-7d50-11e9-9d36-22e25e5736ed.png)
![Auswahl_352](https://user-images.githubusercontent.com/584168/58243272-9f00db80-7d50-11e9-83e0-5f020bb5ed2d.png)

**Comment by jakubpolomsky** [comment]
Hello,

First of all, thank you for your report. You have checked the checkbox that you are using supported version of magento 2. Yet I can see that you are using magento 2.3.1 which of these two is correct? Second thing would be that we would need some steps to reproduce this issue as a simple checkout works well for me. Please elaborate your issue a little more.

Kind regards,
Team Shopsystems @Wirecard

**Comment by roman204** [comment]
Hi Jakub,
thank you for your response, you are right, i am using 2.2.6.

The response data is only wrong nested. As you can see javascript tries to access 
data["redirect-url"] but the object is data.data["redirect-url"]

a quick fix could be like
```
$.get(url.build('wirecard_elasticengine/frontend/callback'), function (data) {
        data = data.data;
        if (data['form-url']) {
          var form = $('<form />', {
            action: data['form-url'],
            method: data['form-method']
          });
          for (var i = 0; i < data['form-fields'].length; i++) {
            form.append($('<input />', {
              type: 'hidden',
              name: data['form-fields'][i]['key'],
              value: data['form-fields'][i]['value']
            }));
          }
          form.appendTo('body').submit();
        } else {
          window.location.replace(data['redirect-url']);
        }
      });
```

then the value is accessible in js via data["redirect-url"]

or change the way how the redirect_url is accessed

**Comment by rinnhofer** [comment]
Hello @roman204 ,

thank you for your detailed explanation. We are already working on this issue and hopefully finish a working release in the next hours.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Thank you very much @roman204  for your fix, but we just triggered a release for this issue which should be available within several minutes. 
We are very gratefull for your contribution and your fast responses to our questions.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Here you can find our latest release to this issue, I hope you don't mind that I will close your pull-request and this issue due to the solution within this release
https://github.com/wirecard/magento2-ee/releases/tag/1.5.1
