### ISSUE TITLE
order placed with no transaction record

### ISSUE THREAD

**Issue by ksaleem25** [wirecard/magento2-ee#269]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.2  
**PHP version:** 7.1  

### Issue

**Problem description:**
After upgrading to the latest version credit card order are being placed without transaction information. as per our findings, seamlessFormSubmitSuccessHandler function is not saving transaction data 
...

**Steps to reproduce:**

Place an order with a credit card and check transaction information in the backend
![no transaction](https://user-images.githubusercontent.com/17887732/62963082-90323e00-be00-11e9-985b-ad81aac1f5f9.PNG)

**Comment by vitali-graz** [comment]
Hi @ksaleem25 
thank you for bringing up this issue to our attention. While we are looking into it, could you please provide our support at shop-systems-support@wirecard.com with the corresponding logs and order states?
Kind regards,
Wirecard Shop Systems Team

**Comment by wigman** [comment]
Is 2.3.2 officially supported yet? The readme says 2.3.1. I'm facing issues as well.

**Comment by vitali-graz** [comment]
The latest supported version is indeed 2.3.1. We tested it again this morning and it works well on our end. At the moment, we recommend not upgrading to 2.3.2 as long as we haven't tested it thoroughly.
Should you be experiencing issues on 2.3.1, please contact our support at shop-systems-support@wirecard.com with some details so that we can address your specific issue.
Kind regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

sorry for the delay. This issue should be resolved with the latest release (2.2.0).
When updating to the latest version please follow the steps listed in the release notes.
https://github.com/wirecard/magento2-ee/releases/tag/2.2.0

Best regards,
Wirecard Shop Systems Team
