### ISSUE TITLE
Error when buying a virtual product with Paypal

### ISSUE THREAD

**Issue by xpoback** [wirecard/magento2-ee#277]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.2.9  
**PHP version:** 7.1.36 
**Module version:** 2.0.1

### Issue

**Problem description:**
Virtual products don't require a shipping address to present in the order. But the module tries to get one from the order and [set it to the transaction](https://github.com/wirecard/magento2-ee/blob/2.0.1/Gateway/Request/PayPalTransactionFactory.php#L82). Since it's a `null`, the AccountHolderFactory throws [an exception](https://github.com/wirecard/magento2-ee/blob/master/Gateway/Request/AccountHolderFactory.php#L46).

**Steps to reproduce:**

1. Put a virtual product to the cart.
2. Chose Paypal as a Payment method in checkout.
3. Try to buy the product.

Expected result: 
 - no exception is thrown.

Actual result: 
 - an exception is thrown.

**Possible solution**
Shipping address does not seem to be mandatory for Paypal transactions. I that case it's possible just to skip it if it's not present in the order.

**Comment by rinnhofer** [comment]
Hello @xpoback ,

thank you for your contribution. We will look into our basket creation with virtual products as soon as possible. In the mean time you could deactivate sending the shopping basket and additional information for PayPal to avoid issues like that.

Kind regards,
Wirecard Shop Systems Team

**Comment by xpoback** [comment]
@rinnhofer Unfortunately, deactivating sending the shopping basket and additional information for PayPal has not helped. At least not in our particular case.

**Comment by rinnhofer** [comment]
Hello @xpoback ,

thank your for the update and sorry that the deactivation did not work out, we already took a look at the code base handling the shipping address parameters and are working on a solution for it.
We will notify you immediately when our next release is tested and deployed.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @xpoback ,

while our release is in progress you could comment/remove the following line, which should solve your issue in the mean time (+ deactivation of send additional information):
https://github.com/wirecard/magento2-ee/blob/d2487faa81df6deb85d0de65fb2aa8077d249cae/Gateway/Request/PayPalTransactionFactory.php#L82

Kind regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @xpoback ,

sorry for the delay. We are currently working on the topic and it will be fixed in our upcoming release!

Best regards,
Wirecard Shop Systems Team

**Comment by xpoback** [comment]
@serucee Do you know when the upcoming release is to be expected, approximately?

**Comment by serucee** [comment]
Hi @xpoback ,

we will release in the course of next week.

Best regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @xpoback ,

today we released a new version of our extension
https://github.com/wirecard/magento2-ee/releases/tag/2.2.1
This release includes additional validation for address data and should fix the issue.

Kind regards,
Wirecard Shop Systems Team
