### ISSUE TITLE
Wrong redirect URL on success

### ISSUE THREAD

**Issue by xpoback** [wirecard/magento2-ee#278]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.2.9 
**PHP version:** 7.1.36
**Module version:** 2.0.1

### Issue

**Problem description:**

This problem does not happen on a clean Magento installation, but this is a compatibility issue whenever a checkout module is installed and can be easily fixed.

If a third party checkout module is installed that uses a custom URL on checkout page, after buying a product with credit card without 3Dsecure the customer gets redirected to `thirdparty/onepage/success` instead of `checkout/onepage/success`.
The reason is that [the redirection path](https://github.com/wirecard/magento2-ee/blob/2.0.1/Controller/Frontend/Redirect.php#L175) does not contain any module name but instead only `onepage/success`.

**Steps to reproduce:**

1. Use a checkout module with a custom URL (like `thirdparty/checkout`).
2. Buy something with Credit Card (non 3Dsecure)

Expected result: the customer gets redirected to a success page `checkout/onepage/success`.

Actual resut: the customer gets redirected to `thirdparty/onepage/success`, which is obviously a 404.

**Possible solution**

Replace `'onepage/success'` with `'checkout/onepage/success'` here: https://github.com/wirecard/magento2-ee/blob/2.0.1/Controller/Frontend/Redirect.php#L175

**Comment by serucee** [comment]
Hi,

thank you for your feedback! We will look into the suggested change and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @xpoback ,

today we released a new version of our extension, which includes fully qualified redirection URLs.
https://github.com/wirecard/magento2-ee/releases/tag/2.2.2

This should resolve issues with custom checkout URLs.

Kind regards,
Wirecard Shop Systems Team
