### ISSUE TITLE
Status "Pending Payment" on successful payment

### ISSUE THREAD

**Issue by xpoback** [wirecard/magento2-ee#280]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.2.9 
**PHP version:** 7.1.36
**Module version:** 2.0.1

### Issue

**Problem description:**
After an order is made with Wirecard Credit Card, the order status stays on "Pending Payment".
The setting "Payment Action" is on "Purchase".

**Steps to reproduce:**

1. Set "Payment Action" in Payment method configuration to "Purchase"
2. Use [testing credentials](https://github.com/wirecard/magento2-ee/wiki/Testing) to place an order.

Expected result: 
1. The customer gets redirected to a success page.
2. An invoice is created and a transaction is present.
4. The order has status "Processing"

Actual result: 
1. :heavy_check_mark: The customer gets redirected to a success page.
2. :heavy_check_mark: An invoice is created and a transaction is present.
3. :x:  The order still has status "Pending Payment" and *not* on "Processing"

**Comment by serucee** [comment]
Hi,

we will look into the described issue and keep you updated. Thank you for your feedback.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi,

sorry for the delay. This issue should be resolved with the latest release (2.2.0).
When updating to the latest version please follow the steps listed in the release notes.
https://github.com/wirecard/magento2-ee/releases/tag/2.2.0

Best regards,
Wirecard Shop Systems Team
