### ISSUE TITLE
Loading of Creditcard Form gives 401 if address is missing

### ISSUE THREAD

**Issue by cebesoft** [wirecard/magento2-ee#295]
### Prerequisites

- [ x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [ x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.2
**PHP version:** 7.1

### Issue

**Problem description:**

When trying to load the creditcard payment form, when user has not entered a shipping address yet, the wpp reacts with an 401 Unauthorized.

Actually I expect the wpp to respond with information, what went wrong and the magento module to display an useful error message instead of "An error occurred loading the credit card form. Please try again.".

With this accomplished, 3rd party modules are able to react in a proper way.

**Steps to reproduce:**

- Install Magento 2.3.2 and configure Wirecard EE
- Install 3rd party checkout extension like Amasty One Step Checkout
- Click on the payment method Wirecard Creditcard before entering address data

**Comment by serucee** [comment]
Hi @cebesoft ,

thank you for your input! Could you add which extension version you are using?
We will look into the issue and keep you updated on the progress.

Best regards,
Wirecard Shop Systems Team

**Comment by cebesoft** [comment]
Hi @serucee,
we use amasty/module-single-step-checkout 2.8.4 (but problem is in my opinion independend from the used 3rd party module).
Best regards,
Bernhard

**Comment by serucee** [comment]
Hi @cebesoft ,

thank you for your quick response. Sorry I didn't specify the question enough - I meant which extension version of our module.

Best regards

**Comment by serucee** [comment]
Hi @cebesoft ,

usually a 401 (Unauthorized) happens when the credentials are incorrect. Is it possible for you to [contact our support](https://github.com/wirecard/magento2-ee/wiki/Contact-Information) so the issue can be analyzed quicker?

Best regards,
Wirecard Shop Systems Team

**Comment by cebesoft** [comment]
Hi @serucee ,

the credentials are correct, since I can load the form and make a creditcard payment, as soon as the shipping address is not empty.

Best regards,
Bernhard

**Comment by rinnhofer** [comment]
Hello @cebesoft ,

we added additional validation for address data within the checkout process in our latest release
https://github.com/wirecard/magento2-ee/releases/tag/2.2.1
which should resolve this issue.

Kind regards,
Wirecard Shop Systems Team
