### ISSUE TITLE
Form_key invalid on cancel controller

### ISSUE THREAD

**Issue by wigman** [wirecard/magento2-ee#305]
The cancel controller does not work since it does not implement the NoCsrfTrait.
It currently redirects to the homepage with the error 'form_key invalid'.

Pull request with fix is here: https://github.com/wirecard/magento2-ee/pull/304

**Comment by rinnhofer** [comment]
Hello @wigman ,

thank you for your contribution. We will look into your pull request as soon as possible and give you notice if it will be included within our next release.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @wigman ,

thank you for your pull-request. We included the changes within our latest release:
https://github.com/wirecard/magento2-ee/releases/tag/2.2.1

Kind regards,
Wirecard Shop Systems Team
