### ISSUE TITLE
Missing transaction-state in response after cancel payment

### ISSUE THREAD

**Issue by gego05** [wirecard/magento2-ee#316]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.3
**PHP version:** 7.2

### Issue

**Problem description:**

While canceling the payment process, an exception throws in /vendor/wirecard/payment-sdk-php/src/Mapper/ResponseMapper.php on line 106.

**Steps to reproduce:**

- Enable credit cart method and fill in production credentials
- Go to frontend and put a product to basket
- Go to checkout and select credit card method
- Fill in correct credit cart data (in this case visa) and click on place order button
- Redirection to card complete (3-D Secure)
- Click on cancle
![wirecard1](https://user-images.githubusercontent.com/16879037/68376461-f51fda80-0148-11ea-80e0-b88c44201dbd.jpg)
- Error occure
![wirecard2](https://user-images.githubusercontent.com/16879037/68376463-f51fda80-0148-11ea-8671-f89f391fc839.jpg)
![wirecard3](https://user-images.githubusercontent.com/16879037/68376464-f51fda80-0148-11ea-84f0-1e50b80901cf.jpg)

**Comment by rinnhofer** [comment]
Hello @gego05 ,

thank you for your contribution. We will take a look at this issue as soon as possible. In the meantime could you please give us information if you get the same behaviour by using test credentials or is this only happening with your production credentials?
Are you using the latest release? (2.2.1)

Kind regards,
Wirecard Shop Systems Team

**Comment by gego05** [comment]
Hello @rinnhofer,

The first test was with version 2.2.0, but today we updated to 2.2.1 and the same error occures (with production data).

We are NOT getting the same behaviour with test data:
- In magento backend fill in demo data in credit card section
- Go to checkout and select credit card
- Fill in demo credit card
- Click on order now
- Redirection to 3-D Secure demo page
![wirecard5](https://user-images.githubusercontent.com/16879037/68464362-cff69f00-0210-11ea-8095-750ce1963996.jpg)
- Click on cancel
- Redirection to magento cart
- No error occures

Thanks for your help.

**Comment by gego05** [comment]
Hello @rinnhofer,

After a few more tests, we noticed, that this error not just occures when we cancel the payment.
This is also happening when we make a correct payment. After the 3D secure page this error occures.

This is now a big problem for us. Can you please help us?
Maybe this is just due to misconfiguration or false credentials.

Thanks.

**Comment by gego05** [comment]
So, the response we are getting in
`public function map($response, Transaction $transaction = null)`
is 
`<html><head><title>401 Unauthorized</title></head><body><h1>Unauthorized</h1></body></html>`.

This is strange, because we have a magento 1 shop running with the same credentials.

**Comment by rinnhofer** [comment]
Hello @gego05 ,

thank you for your detailed explanation - maybe you could contact our technical support (shop-systems-support@wirecard.com) for more specific help. They could help to verify if your credentials are correct and give our development team more information on how to test this scenario in our test system to prevent this from happening.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @gego05 

since we did not hear from you again I assume your issue has been resolved or that our technical support was able to help, therefor I will close this issue.

If there are still issues or help is needed you can open a new issue any time or contact our support.

Kind regards,
Wirecard Shop Systems Team
