### ISSUE TITLE
PayPal orders successful but pending_payment, then cancelled

### ISSUE THREAD

**Issue by avoelkl** [wirecard/magento2-ee#317]
### Prerequisites

- [X] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [X] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.3
**PHP version:** 7.2

### Issue

**Problem description:**
We are having problems with PayPal orders in foreign currencies such as HUF, SEK, CZK, PLN via **test mode**. We can post successful orders (most of the time) but then the order status stays "pending payment" and after a while gets cancelled.

I assume this is related to the messages that we see in the log:
```
[2019-11-07 09:32:11] main.ERROR: Response is malformed: Missing statuses in response. [] []
[2019-11-07 09:32:11] main.ERROR: WirecardTransactionUpdater::exception:Missing statuses in response. [] []
```
...

**Steps to reproduce:**
1. Create Order with foreign currency SEK, HUF, PLN, CZK in **test mode**
2. Successful order
3. Check order status - pending_payment
4. Order does not get updated to "processing" by cron but cancelled after a while
...

**Comment by avoelkl** [comment]
I can provide according transaction_ids if needed via another channel ;-)

**Comment by rinnhofer** [comment]
Hello @avoelkl ,

thank you for contributing so actively.
Sadly our test system does not support the same currencies like our production system.
We will forward this topic to our internal documentation to avoid further confusion with the supported currencies within our test system.
For now I would recommend to only use "EUR" on our test system.

If you have further questions about our test system or you want to share more detailed information over a different channel, feel free to contact our technical support at shop-systems-support@wirecard.com.

We will also look into the processing of responses within our extension to ensure the error handling for incompatible responses from the test system does not lead to this behavior in the future.

Kind regards,
Wirecard Shop Systems Team

**Comment by avoelkl** [comment]
Hi @rinnhofer,
Thanks a lot for your quick and helpful reply!

Testing in EUR only is not really an option as our merchant wants to test orders with all these currencies before going live (they will be available in the live environment later on as well). BUT: so far you are the first one to tell us that this is not possible at all.

We already raised a lot of tickets regarding PayPal/Test environment and various problems (for example missing invoices with foreign currencies) with the technical support via e-mail but it takes them ages to reply (if they reply at all..).

However, we will discuss it internally and with our merchant on how to continue with this.

Thanks again for your help!
