### ISSUE TITLE
Cannot Install Wirecard on M2.3.3 CE

### ISSUE THREAD

**Issue by ecompleteClem** [wirecard/magento2-ee#322]
### Prerequisites

- [X ] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [X ] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:* 2.3.3 * ...  
**PHP version:* 7.2.24* ...  

### Issue

Composer install fails

**Problem description:**

  Problem 1
    - Can only install one of: myclabs/php-enum[1.7.2, 1.6.6].
    - Can only install one of: myclabs/php-enum[1.6.6, 1.7.2].
    - Can only install one of: myclabs/php-enum[1.6.6, 1.7.2].
    - wirecard/payment-sdk-php 3.8.1 requires myclabs/php-enum 1.6.6 -> satisfiable by myclabs/php-enum[1.6.6].
    - wirecard/magento2-ee 2.2.1 requires wirecard/payment-sdk-php 3.8.1 -> satisfiable by wirecard/payment-sdk-php[3.8.1].
    - Installation request for wirecard/magento2-ee 2.2.1 -> satisfiable by wirecard/magento2-ee[2.2.1].
    - Installation request for myclabs/php-enum (locked at 1.7.2) -> satisfiable by myclabs/php-enum[1.7.2].

...

**Steps to reproduce:**

composer require wirecard/magento2-ee

...

**Comment by rinnhofer** [comment]
Hello @ecompleteClem ,

thank you for your contribution. We are currently supporting various PHP versions within our wirecard/payment-sdk-php, which includes PHP versions < 7.2. Therefor we can only support myclabs/php-enum < 1.7.0 due to incompatibility to PHP versions <7.2 starting with version 1.7.0.
For more details on myclabs/php-enum version support: https://packagist.org/packages/myclabs/php-enum#1.7.0

During our tests within Magento2 we did not encounter any problems with this package version. It could be that this package is required from an additional third-party plugin within your installation too. Could you please share with us which additional package within your installation requires myclabs/php-enum and in which version range so we can evaluate if there is a possibility to resolve the conflicts?

Kind regards,
Wirecard Shop Systems Team

**Comment by ecompleteClem** [comment]
./vendor/endroid/qr-code/composer.json:        "myclabs/php-enum": "^1.5"

**Comment by ecompleteClem** [comment]
When you run:

composer require wirecard/payment-sdk-php

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for wirecard/payment-sdk-php ^4.0 -> satisfiable by wirecard/payment-sdk-php[4.0.0].
    - wirecard/payment-sdk-php 4.0.0 requires myclabs/php-enum ~1.5.0 || ~1.6.0 -> satisfiable by myclabs/php-enum[1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by ecompleteClem** [comment]
in my global composer.json I have

"require": {
        "interjar/bugsnag": "^2.3",
        "magento/product-community-edition": "2.3.3",
        "myclabs/php-enum": "^1.7"
    },

**Comment by ecompleteClem** [comment]
So it looks like your SDK does not support myclabs/php-enum ^1.7 hence it failing to install.

**Comment by ecompleteClem** [comment]
That is why it is trying to install 2X Versions of it when you require the original composer package.

**Comment by ecompleteClem** [comment]
When are you going to update your module dependencies + versions? We are not at liberty to downgrade other dependencies to use your module.

**Comment by ecompleteClem** [comment]
I have downgraded myclabs/php-enum to 1.6 and I still receive an error installing.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wirecard/payment-sdk-php 3.8.1 -> satisfiable by wirecard/payment-sdk-php[3.8.1].
    - wirecard/payment-sdk-php 3.8.1 requires php-http/client-implementation ~1.0 -> no matching package found.

Thereafter I require the php-http/client-implementation 

[InvalidArgumentException]                                                                                                                                                                               
  Could not find a matching version of package php-http/client-implementation. Check the package spelling, your version constraint and that the package is available in a stability which matches your mi  
  nimum-stability (stable).

**Comment by ecompleteClem** [comment]
After a long battle, of Downgrading and Upgrading myclabs/php-enum, I could get your module to install on myclabs/php-enum:1.6.6.

For anyone in the future that needs to install this module. 

composer require myclabs/php-enum:1.6.6
composer require wirecard/magento2-ee

Works with M2.3.3 CE.

**Comment by rinnhofer** [comment]
Hello @ecompleteClem ,

sorry that there were that many troubles with the installation process and the dependencies. Glad that you found a workaround to resolve the dependencies.
We will update our dependencies within the next major release and hopefully can then resolve some of these issues in the future.

Kind regards,
Wirecard Shop Systems Team
