### ISSUE TITLE
Error creating orders in test mode with PayPal

### ISSUE THREAD

**Issue by avoelkl** [wirecard/magento2-ee#323]
### Prerequisites

- [X] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [X] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.3
**PHP version:** 72.

### Issue

**Problem description:**
We suddenly see a problem while placing orders with PayPal in test mode in the EUR store: 

> "An error occured on the server. Please try to place the order again."

This is the entry from the exception log
```
==> var/log/exception.log <==
[2019-11-21 12:22:19] main.CRITICAL: State has not been provided. Please check your input and try again.<br>
 {"exception":"[object] (Psr\\Log\\InvalidArgumentException(code: 0): State has not been provided. Please check your input and try again.<br>
 at /vendor/wirecard/magento2-ee/Gateway/Command/WirecardCommand.php:132)"} []
```
It seems this is the response from wirecard, that requires a state.
A state for (in this case our italian address) is not required in Magento:
![image](https://user-images.githubusercontent.com/1798594/69338227-fc73d780-0c62-11ea-96aa-0118b70e766a.png)

**Steps to reproduce:**
1. Create an order in a store with currency EUR
2. Fill out the billing and shipping address for a country where the state is not required
3. Receive the error message in the frontend (checkout)

**Comment by rinnhofer** [comment]
Hello @avoelkl ,

thank you for your contribution. Can you please clarify if this happens with an Italian address or with an Ireland address? In your screenshot Ireland is selected but in your description you are using an Italian address.
If it is an Italian address then state must be provided as it is stated in the PayPal documentation:
https://developer.paypal.com/docs/classic/api/state-codes/

Kind regards,
Wirecard Shop Systems Team

**Comment by avoelkl** [comment]
Hi @rinnhofer 
Oh, thanks for the link!
It seems we accidentally ran into this as we updated the config to be only required for Ireland. Thanks!
