### ISSUE TITLE
 currency rate  not applied

### ISSUE THREAD

**Issue by TomSchlo** [wirecard/magento2-ee#330]
- [ X] I have my server set up correctly.
- [X ] I am using a supported version of Magento

Magento 2.3.3
PHP 7.3

### Issue
If a customer change the currency in our shop and check out with Wirecard Credit Card, the amount isn't changed by currency rate to the standard currency of the shop, but 1:1.

**Steps to reproduce:**

Change currency in frontend to PLN -> checkout with setting standard currency EURO in Wirecard ee plugin -> 450 PLN will be 450 EUR.

**Comment by rinnhofer** [comment]
Hello @TomSchlo ,

thank you for reporting this issue. We will look into the currency conversion as soon as possible and inform about upcoming releases.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @TomSchlo ,

today we released a new version of our extension, which should resolve this issue:
https://github.com/wirecard/magento2-ee/releases/tag/2.2.2

Kind regards,
Wirecard Shop Systems Team
