### ISSUE TITLE
Latency for the api.wirecard.com from South East Asia region

### ISSUE THREAD

**Issue by hammad-k-dar** [wirecard/magento2-ee#338]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:*2.3.4* ...  
**PHP version:*7.1.33* ...  

### Issue

**Problem description:**
We are experiencing slowness for the below call when this call is made from South East Asia region.

![image](https://user-images.githubusercontent.com/28210356/70140499-a5d0b980-16b6-11ea-8785-9516462ac668.png)

The IP being resolved after the lookup of api.wirecard.com is a germany based IP.

Could you please share the feedback?
...

**Steps to reproduce:**
Call the api from Korea or Japan country (use proxy)
https://api.wirecard.com/engine/includes/i18n/languages/hpplanguages.json
...

**Comment by manfredhoelzl** [comment]
Hi Hammad-k-dar

in this section you can aks questions and report bugs regarding the shop extensions. This seams to be a connection problem with the api itself. Regarding this please contact support@wirecard.com

BR
Manfred
Shop Systems Support
