### ISSUE TITLE
Magento 2 Order confirmation email sent out BEFORE Payment completed

### ISSUE THREAD

**Issue by sradinger** [wirecard/magento2-ee#339]
### Prerequisites

- [ ] I am using Magento 2.3.3 
- [ ] I have installed the current Version from magento2-ee (2.2.2) 
- [ ] Checkout with Payment Method "Wirecard Sofort" with DEMO credentials

### Versions
Magento version: 2.3.3
PHP version: 7.2

### Issue
Checkout with wirecard sofort payment (with demo credentials).
Order confirmation email is sent before payment completed. 
When I canceled payment on the klarna payment page i have already received the e-mail.

The e-mail should be sent only after successful payment!

**Steps to reproduce:**
Checkout with wirecard sofort payment (with demo credentials).
Cancel the Payment on the klarna payment Page

**Comment by rinnhofer** [comment]
Hello @sradinger ,

thank you for your contribution. We will look into the workflow for order confirmations in combination with Magento2 standards and give you feedback on how we will proceed with this issue as soon as possible.

In the mean time could you please verify if the order confirmation, you receive before the actual payment, includes information about the payment state or if it is only a confirmation for a successful order creation?

Kind regards,
Wirecard Shop Systems Team

**Comment by asannikov** [comment]
Have the same problem. I get successful order confirmation.

**Comment by Khamulus** [comment]
Got the same problem. Is there any Workaround for the moment?

**Comment by rinnhofer** [comment]
Hello,

we are currently working on a solution design for this issue to ensure that we are not breaking other workflows. If you are searching for a workaround for now, you could disable Sales Mail for "Order" and only keep it enabled for "Invoice" to only send mails to customers with paid orders.

We will send updates here as soon as we are finished with our solution design for this issue.

Kind regards,
Wirecard Shop Systems Team

**Comment by whuber** [comment]
Any solution for this? We have the same problem...!

**Comment by Khamulus** [comment]
@rinnhofer Any News on this topic?

Our customers are asking us weekly about this problem.

**Comment by knospe-** [comment]
@rinnhofer Any news on this issue? Why is this taking more than 6 Months with no fix?

**Comment by xpoback** [comment]
@sebastijansakac @rinnhofer Has there been any progress?
The same problem happens even in the latest version (3.1.3) when using Paypal: the order is created and the email comes before the payment is completed.
It's a huge problem, please try to allocate some resources to fix these old issues first.

**Comment by cpfoser** [comment]
Dear all, 

sorry for the late update. 
From a product solution design we do not treat this issue as a "bug" because this decision was taken consciously. After several discussion we decided to stay with the current implementation. 

Reasons: 
1.) Order confirmation are sent at the point where shop-systems create the order (when consumer clicks "order with an obligation to pay")
2.) If we would wait until the payment has been paid, we would run in the problem that merchant do not have an up to date information in regards of turnover, stock-information --> because orders will not be created for a certain time period. (problems with captures for authorization payments will occur, or SEPA has an extended time period until the confirmation is there that the consumer has acutally paid)

We will stay with the current solution despite the fact that: 
- merchants need to take care how to configure order confirmation within the shop-system
- and consumers need to be informed that those two mails have different purposes. 

Thank you for your understanding!

Kind regards, 
Wirecard Shop Systems Team

**Comment by whuber** [comment]
For our customer this makes no sense, as the customer should receive an order confirmation only when the order is finally payed. Currently the customer receives an order confirmation even if they cancel the payment so they are confused about receiving an order confirmation. Maybe it's not a bug but a feature - but it should be configurable in the Magento backend.

**Comment by knospe-** [comment]
You are the only Magento payment module that I know with this kind of logic, which does not make any sense to me. And to provide this answer 6 months after the issue has been reported is just a sign of bad service. I must agree with @whuber

**Comment by xpoback** [comment]
> Order confirmation are sent at the point where shop-systems create the order 

1. It is possible to create an order without sending an email, wait until the customer either pays or cancels the payment and then confirm or cancel the order correspondingly.

> we would run in the problem that merchant do not have an up to date information in regards of turnover, stock-information

2. Maybe this would surprise you, but there are order statuses in Magento exactly for this, and also stock information is updated upon invoicing/shipment, not upon sending emails.

> problems with captures for authorization payments will occur, or SEPA has an extended time period until the confirmation is there that the consumer has actually paid

3. Still not getting how sending a premature email could help solve this possible issue?

**Comment by avoelkl** [comment]
I run into this issue yesterday as well while testing #444. Sending out an order confirmation e-mail while the customer is still stuck in the checkout (in this case with 2.3.5) and has not successfully payed and placed an order is really a big problem.
