### ISSUE TITLE
Magento 2.3.3 support

### ISSUE THREAD

**Issue by AlexSlovinskiy** [wirecard/magento2-ee#345]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [ ] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.3.  
**PHP version:** 7.2  

### Issue

**Problem description:**

I'm wondering when it's possible to get Magento 2.3.3 support. Downgrade to lower Magento version is not a working case.

**Comment by rinnhofer** [comment]
Hello @AlexSlovinskiy ,

if you are using our newest magento2-ee release Magento 2.3.3 should be already supported.
We added compatibility with Magento 2.3.3 with the following release:
https://github.com/wirecard/magento2-ee/releases/tag/2.2.1

Kind regards,
Wirecard Shop Systems Team
