### ISSUE TITLE
payment sdk and myclabs/php-enum

### ISSUE THREAD

**Issue by 22markets** [wirecard/magento2-ee#357]
Problem on installing module via composer. I have myclabs/php-enum 1.7.2 installed but the sdk is only up to 1.6.6

Problem 1
    - Can only install one of: myclabs/php-enum[1.7.2, 1.6.6].
    - Can only install one of: myclabs/php-enum[1.6.6, 1.7.2].
    - Can only install one of: myclabs/php-enum[1.6.6, 1.7.2].

**Comment by flavius** [comment]
Hi @22markets 

We are aware of this issue and we're working on it.

The fix will be included in one of the upcoming releases.

Please keep an eye on the changelog.

Kind regards,
Wirecard Shop Systems Team

**Comment by vitali-graz** [comment]
Hi @22markets 
Issue resolved with the latest Magento 2 [release v.3.1.0](https://github.com/wirecard/magento2-ee/releases/tag/v3.1.0).

Best regards,
Wirecard Shop Systems Team
