### ISSUE TITLE
SEPA Direct Debit missing 'capture' transaction

### ISSUE THREAD

**Issue by flamboy** [wirecard/magento2-ee#375]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

**Magento version:** 2.3.2-p2
**PHP version:** 7.2
**Plugin name:** Wirecard_ElasticEngine
**Plugin version:** 3.0.1

### Issue

**Problem description:**

After checkout purchase via 'SEPA Direct Debit', order stucks at 'Pending Payment' status.

**Steps to reproduce:**

1. Set-up test credentials in admin panel for 'SEPA Direct Debit' payment method
2. Choose 'Purchase' payment action https://i.imgur.com/5VqRdEk.png
3. Clean-up caches
4. Make an order via SEPA DD on checkout page
5. After amount of time order stucks at 'Pending Payment' status. 
After 8 hr Magento set order status to 'Cancel' -> it's default behavior

**Prerequisites**

Here what we have in logs

```
[2020-02-20 08:20:09] main.INFO: Cron Job wirecard-update-payments is run [] []
[2020-02-20 08:20:09] main.INFO: WirecardTransactionUpdater::found 2 payments [] []
[2020-02-20 08:20:12] main.DEBUG: WirecardTransactionUpdater::transaction:276 order:368 no notify found [] []
[2020-02-20 08:20:12] main.INFO: Cron Job wirecard-update-payments is successfully finished. Statistics: {"sum":3.3058469295502,"count":1,"realmem":6291456,"emalloc":5855304,"realmem_start":77856768,"emalloc_start":76198272} [] []
```

So, looks like some logic missing for this payment method here https://github.com/wirecard/magento2-ee/blob/v3.0.1/Gateway/Model/TransactionUpdater.php#L183-L205

Also at admin panel, we have only 'order' transaction type 
https://i.imgur.com/A5SAwO4.png

Need 'capture' transaction too.

**Debug results**

Found that Wirecard module try to get transaction by URL (example):
https://api-test.wirecard.com/engine/rest/merchants/933ad170-88f0-4c3d-a862-cff315ecfbc0/payments/search?payment.request-id=bfb455c0d482867aa4aef70f60b993ee
& nothing found
But real transaction here 
https://api-test.wirecard.com/engine/rest/merchants/933ad170-88f0-4c3d-a862-cff315ecfbc0/payments/search?payment.request-id=bfb455c0d482867aa4aef70f60b993ee-pending-debit

Also for order with 'authorization' payment type
https://api-test.wirecard.com/engine/rest/merchants/933ad170-88f0-4c3d-a862-cff315ecfbc0/payments/search?payment.request-id=71045c900941fc06564b36a0d3aea5b6-authorization

**Comment by rinnhofer** [comment]
Hello @flamboy ,

sadly our test system does not send notifications for SEPA Direct Debit, that is why your order is stuck in **"Pending Payment"** status. In production you should receive SEPA Direct Debit notifications in about 2 business days as described here: [https://doc.wirecard.com/SEPADirectDebit_Rest.html#SEPADirectDebit_Workflow](https://doc.wirecard.com/SEPADirectDebit_Rest.html#SEPADirectDebit_Workflow)

Currently within our implementation we are requesting the payment status with a cron job, this results in the TransactionUpdater logs you mentioned above. (in default setup this happens every 15 minutes)

Magento2 provides a setting within your Shop configuration in the Sales section called "Orders Cron Settings" with the field **"Pending Payment Order Lifetime (minutes)"** where you can configure when to automatically cancel pending orders.

I hope I could help you with this information, if you have any further questions feel free to open a new issue.

Kind regards,
Wirecard Shop Systems Team
