### ISSUE TITLE
Status "Pending Payment" on successful payment

### ISSUE THREAD

**Issue by roman204** [wirecard/magento2-ee#411]
### Prerequisites
 
* [x]  I have my [server set up correctly](https://github.com/wirecard/magento2-ee/wiki/Installation#requirements).
 
* [x]  I am using a [supported version of Magento](https://github.com/wirecard/magento2-ee/wiki#overview-magento-2-shop-plugin).

### Versions

 **Magento version:** 2.3.3
**PHP version:** 7.2.24
**Module version:** 3.0.0

### Issue
**Problem description:**
After an order is made with Wirecard Credit Card, the order status stays on "Pending Payment".
The setting "Payment Action" is on "Purchase".
Also in system.log the following error gets logged :
> main.ERROR: Warning: SimpleXMLElement::addChild(): unterminated entity reference in /vendor/wirecard/payment-sdk-php/src/Mapper/ResponseMapper.php on line 302

**Steps to reproduce:**
1. Set "Payment Action" in Payment method configuration to "Purchase"
2. Use [testing credentials](https://github.com/wirecard/magento2-ee/wiki/Testing) to place an der.
 
Expected result:
1. The customer gets redirected to a success page.
2. An invoice is created and a transaction is present.
3. The order has status "Processing"

Actual result:
1. heavy_check_mark The customer gets redirected to a success page.
2. heavy_check_mark An invoice is created and a transaction is present.
3. x  The order still has status "Pending Payment" and _not_ on "Processing"

**Comment by tomazpu** [comment]
Hello @roman204,

I suggest updating to the newest version of our plugin and testing again. We were unable to recreate the problem. If you still have the same problem please reopen the ticket. Best case with more information about the setup. The best way of checking for such problems is with are shop-systems-support@wirecard.com

Best regards
Tomaz

**Comment by roman204** [comment]
Thank you for closing, we did a update to 3.1.1 and the result ist the same.... We didn't even notice any requests to wirecard_elasticengine/notify in access.log...

**Comment by tomazpu** [comment]
In this case please contact the support, it very difficult to reproduce such an issue without having a check on your system.

You can check the debug.log for requests and responses.

Best regards,
Tomaz
